### ISSUE TITLE
Feature Todo:

### ISSUE THREAD

**Issue by thybag** [thybag/RPGCampaignManager#1]
Left side bar;
- [x] Filtering support (pull from api, vs render from blade) - filter each section collapsing when empty
- [x] Section collapsing on click
- [x]  Add new section

CSS
- [ ]  General cleanup in to files + improve look/feel
- [x]  Retire bootstrap - port login to internal styles

Entities
- [x] Fire entity added event to handle adding to map/sidebar without reload
- [x]  Entity menu - make a menu (Options  Edit/Hide/Remove (With confirm))
- [x]  Make the "Locate" buttons smarter - Show create when none exist & choice of poly line or marker.
- [x]  Edit button to trigger edit on point

Top Bar;
- [x]  Better selected state /
- [x]  Top menu - use real name - drop down (Campaign settings / Main Menu / Logout)

Map:
- [ ] Smarter initial zoom level (based on map size)
- [ ] Upload custom icons (players)

Infra:
- [ ] All in one docker container for easy self host

Blocks:
- [x]  Drag to upload images in to block (ala github)
- [x]  remove button
- [ ]  block "types" - text/statblock
- [x] Markdown explanation text

Tests:
- [x]  Basic api functionality

API:
- [x]  Setup requests to validate input properly
- [ ]  Implement rest of endpoints
- [ ]  Email verification if not in local mode
- [ ] Update to Laravel 8
